name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0

      - name: Set up Node.js 18.17.0
        uses: actions/setup-node@v3.7.0
        with:
          node-version: 18.17.0

      - name: Install dependencies
        run: npm i

      - name: Run ESLint
        run: npx lerna run eslint

      - name: Run tests
        run: npx lerna run test
