name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Set up Node.js 18.17.0
        uses: actions/setup-node@v4.0.1
        with:
          node-version: 18.17.0

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run eslint

      - name: Run tests
        run: npm run test
