name: Update Release Log

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  update-release-log:
    permissions:
      # Write permission is required to create a GitHub release.
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Generate release log
        uses: release-drafter/release-drafter@v6.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
